apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    # storage size
    storage: 10Gi
  accessModes:
    # ReadWriteMany(RW from multi nodes), ReadWriteOnce(RW from a node), ReadOnlyMany(R from multi nodes)
    - ReadWriteMany
  persistentVolumeReclaimPolicy:
    Retain # retain even if pods terminate
  nfs:
    # NFS server's definition
    path: /srv/nfs/kubedata
    server: {nfs_server_ip}
    readOnly: false